### ISSUE TITLE
Void Cells fail to give items.

### ISSUE THREAD

**Issue by AwesomeSoul** [TheMysticSword/MysticsItems#100] opened 2021-04-08 07:43 UTC
After fully charging a Void Cell it fails to give any items.

**Comment by TheMysticSword** [comment] 2021-04-08 11:26
Do you have SivsItems installed? People reported this exact bug with that mod.

**Comment by DragonTrainerBen** [comment] 2021-04-08 15:39
Haven't had this issue with "MysticItems" specifically.
"SivsItems" was pointed out, this is also an issue with the current "TILER2", a dependency for certain item mods.

**Comment by TheMysticSword** [comment] 2021-04-08 15:48
Oh, alright, so it *is* a bug caused by other mods. Thanks for the info! I'll close this then as it's not something I can fix.

**Closed by TheMysticSword** 2021-04-08 15:48 UTC
Labels: bug

**Comment by AwesomeSoul** [comment] 2021-04-08 16:06
> Do you have SivsItems installed? People reported this exact bug with that mod.

I do not have that mod installed. I have Tiller2 for Classic Items, however, while I was testing I disabled Mythic Items (and only that mod) and it fixed the issue. 
Not sure if that helps, I tested it in 1.16, so I'm not sure if 1.17 fixed it, but I'll test later tonight. I'll also try and see if disabling tiller and classic items fixes it also.
