### ISSUE TITLE
Wrench doesn't work.

### ISSUE THREAD

**Issue by Nordblum** [TheMysticSword/MysticsItems#20] opened 2021-03-10 21:11 UTC
Steps to reproduce:
1. Pick up the Wrench (the active item that "gives a free item after using 3D printer and then breaks it")
2. Go to any 3D printer
3. Press a button to activate your active equipment.
3. Interact with 3D printer

Expected behavior: I get a free item that a certain 3D printer prints and then 3D printer breaks, becomes non-interactable. One charge of the Wrench is consumed.

What happens instead: no charge is consumed, 3D printer works as usual, taking one of my items and printing its shown item. It doesn't break after the first use, meaning that the Wrench has absolutely no effect.

**Comment by danielkillsya2** [comment] 2021-03-11 03:26
Same issue here.

**Comment by gaforb** [comment] 2021-03-12 12:08
Just wanted to say I had it work in singleplayer with no problems as part of a large modpack so this may be a mod conflict rather than an inherent bug. Not yet confirmed working in multiplayer

**Comment by TheMysticSword** [comment] 2021-03-12 12:20
Did you try looking at a printer with the wrench equipped? It should create this indicator over it, like a Royal Capacitor over an enemy.
![image](https://user-images.githubusercontent.com/26709843/110939422-38024b80-8357-11eb-9f58-9f5847440076.png)

**Comment by danielkillsya2** [comment] 2021-03-12 14:25
I was playing multiplayer at the time, and the host tried, I tried, and one other person tried.
That icon did not show at that time.

**Comment by TheMysticSword** [comment] 2021-03-14 14:20
The mod now ensures that a custom target searcher exists on the equipment slot every frame, preventing this bug from happening. Closing until this issue occurs again

**Comment by TheMysticSword** [comment] 2021-03-14 18:42
Still happens. Turns out DebugToolkit somehow makes half of the mod work.

**Closed** 2021-03-14 19:03 UTC
Labels: bug
